# docker-compose
# --------------
# This dockerfile is used by the `docker-compose.yml` adjacent file. When
# running `docker-compose build`, this dockerfile helps build the "webapp" image.
# All paths are relative to the `context`, which is the project root directory.
#
# docker build
# --------------
# If you would like to use this dockerfile to build and tag an image, make sure
# you set the context to the project's root directory:
# https://docs.docker.com/engine/reference/commandline/build/
#
#
# SUMMARY
# --------------
# This dockerfile has two stages:
#
# 1. Building the React application for production
# 2. Setting up our Nginx (OpenResty*) image w/ step one's output
#
# * OpenResty is functionally identical to Nginx with the addition of Lua out of
# the box.


# Stage 1: Build the application
FROM node:18.16.1-slim as builder
ARG ZVIEWER_HOST
ARG ZVIEWER_APP_CONFIG

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y build-essential python3

ENV APP_CONFIG=${ZVIEWER_APP_CONFIG}
ENV HTML_TEMPLATE=zmed-index.html
ENV PUBLIC_URL=https://${ZVIEWER_HOST}/
ENV QUICK_BUILD true

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
COPY yarn.lock /usr/src/app/yarn.lock

ADD . /usr/src/app/
RUN yarn config set workspaces-experimental true
RUN yarn install
RUN yarn run build:dev

# Stage 2: Bundle the built application into a Docker container
# which runs openresty (nginx) using Alpine Linux
# LINK: https://hub.docker.com/r/openresty/openresty
FROM openresty/openresty:alpine-fat

#sed -i 's/{ZVIEWER_HOST}/${ZVIEWER_HOST}/g' /usr/local/openresty/nginx/conf/nginx.conf

RUN mkdir /var/log/nginx
#RUN apk add --no-cache openssl
RUN apk add --no-cache openssl-dev
RUN apk add --no-cache git
RUN apk add --no-cache gcc
# !!!
RUN luarocks install lua-resty-openidc

#
RUN luarocks install lua-resty-jwt
RUN luarocks install lua-resty-session
RUN luarocks install lua-resty-http
# !!!
#RUN luarocks install lua-resty-openidc
#RUN luarocks install luacrypto

# Copy build output to image
# COPY --from=builder /usr/src/app/build /var/www/html
# COPY --from=builder /usr/src/app/platform/viewer/dist /var/www/html
COPY --from=builder /usr/src/app/platform/app/dist /var/www/html

ENTRYPOINT ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
